/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("com.fasterxml.jackson.core:jackson-databind:2.16.0")
    implementation("org.reflections:reflections:0.10.2")
    implementation("org.slf4j:slf4j-simple:1.7.32")
    implementation("org.javatuples:javatuples:1.2")
    implementation("org.apache.commons:commons-lang3:3.14.0")


    compileOnly("org.projectlombok:lombok:1.18.30")
    annotationProcessor("org.projectlombok:lombok:1.18.30")

    // Use JUnit test framework.
    testImplementation("junit:junit:4.13.2")
    testImplementation("org.slf4j:slf4j-simple:1.7.32")


    // This dependency is used by the application.
    implementation("com.google.guava:guava:32.1.3-jre")
}

application {
    // Define the main class for the application.
    mainClass.set("Advent.of.Code.Java.App")
}
